project:
  type: website

website:
  title: "Nipun Nambiar"
  repo-url: https://github.com/NRNambiar99/BlogFiles
  repo-actions: [source]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd	

format:
  html:
    theme: quartz
    css: styles.css
    toc: true



